# php 安装

# 安装包拷贝
- name: "php install packge copy"
  copy:
    src: php-{{ php_version }}.tar.gz
    dest: "{{ software_save_path }}"
    owner: root
    group: root
  tags:
    - php_make

# 判断是否已经安装
- name: "php already install ?"
  shell: . /etc/profile && . /etc/bashrc && test -f {{ software_install_path }}/php/bin/php ; echo $?
  register: result_install
  changed_when: result_install['stdout']|int != 0
  tags:
    - php_make

# 如果没有安装，则：解压、编译、构造、安装
- name: "php package uncompress, compile, make and make install"
  # 加载环境变量；进入软件包存放路径，删除已解压目录（如果存在的话），解压包；编译；构造；安装
  shell: . /etc/profile && . /etc/bashrc && (cd {{ software_save_path }} && rm -fr php-{{ php_version }} && tar xf php-{{ php_version }}.tar.gz) && cd {{ software_save_path }}/php-{{ php_version }}/ && {{ php_compile }} && touch ext/phar/phar.phar && make && make install && ln -s {{ software_install_path }}/php-{{ php_version }} {{ software_install_path }}/php
  when: result_install['stdout']|int != 0
  tags:
    - php_make

