# 这里安装包直接使用阿里云的，因此实际可以省略 repository.yml 这步
# yum 安装 zabbix server
- name: "zabbix server package install"
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - "{{ zabbix_server_mysql }}"
    - "{{ zabbix_web_mysql }}"
    - "{{ zabbix_web }}"
    - "{{ zabbix_get }}"
    # 默认安转的包来源于国外，很有可能安装失败，因此这里使用阿里云提供的安装包
    #- zabbix-server-mysql
    #- zabbix-web-mysql
    #- zabbix-get
  tags:
    - zabbix_server

