# nginx 安装

# 安装包拷贝
- name: "nginx install packge copy"
  copy:
    src: nginx-{{ nginx_version }}.tar.gz
    dest: "{{ software_save_path }}"
    owner: root
    group: root
  tags:
    - nginx_make

# 判断是否已经安装
- name: "nginx already install ?"
  shell: . /etc/profile && . /etc/bashrc && test -f {{ software_install_path }}/nginx/sbin/nginx ; echo $?
  register: result_install
  changed_when: result_install['stdout']|int != 0
  tags:
    - nginx_make

# 如果没有安装，则：解压、编译、构造、安装
- name: "nginx package uncompress, compile, make and make install"
  # 加载环境变量；进入软件包存放路径，删除已解压目录（如果存在的话），解压包；编译；构造；安装
  shell: . /etc/profile && . /etc/bashrc && (cd {{ software_save_path }} && rm -fr nginx-{{ nginx_version }} && tar xf nginx-{{ nginx_version }}.tar.gz) && cd {{ software_save_path }}/nginx-{{ nginx_version }}/ && ./configure --prefix={{ software_install_path }}/nginx-{{ nginx_version }} --user=www --group=www --with-http_ssl_module --with-stream --with-http_stub_status_module --with-file-aio && make && make install && ln -s {{ software_install_path }}/nginx-{{ nginx_version }} {{ software_install_path }}/nginx
  when: result_install['stdout']|int != 0
  tags:
    - nginx_make

