# mysql 安装

# 安装包拷贝
- name: "mysql install packge copy"
  copy:
    src: mysql-{{ mysql_version }}.tar.gz
    dest: "{{ software_save_path }}"
    owner: root
    group: root
  tags:
    - mysql_make

# mysql 用户组默认是 27
- name: "mysql group add"
  group:
    name: mysql
    gid: 27
    system: yes
  tags:
    - mysql_make

# mysql 用户默认是 27
- name: "mysql user add"
  user:
    name: mysql
    uid: 27
    group: mysql
    system: yes
    shell: /sbin/nologin
    create_home: no
  tags:
    - mysql_make

# 判断是否已经安装
- name: "mysql already install ?"
  shell: . /etc/profile && . /etc/bashrc && test -f {{ software_install_path }}/mysql/bin/mysql ; echo $?
  register: result_install
  changed_when: result_install['stdout']|int != 0
  tags:
    - mysql_make

# 如果没有安装，则：解压、编译、构造、安装
- name: "mysql package uncompress, compile, make and make install"
  # 加载环境变量；进入软件包存放路径，删除已解压目录（如果存在的话），解压包；编译；构造；安装
  shell: . /etc/profile && . /etc/bashrc && (cd {{ software_save_path }} && rm -fr mysql-{{ mysql_version }} && tar xf mysql-{{ mysql_version }}.tar.gz) && cd {{ software_save_path }}/mysql-{{ mysql_version }}/ && {{ mysql_compile }} && make && make install && ln -s {{ software_install_path }}/mysql-{{ mysql_version }} {{ software_install_path }}/mysql
  when: result_install['stdout']|int != 0
  tags:
    - mysql_make

# 添加MySQL的环境变量
- name: "mysql env add"
  blockinfile:
    path: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK mysql env ###"
    block: |
      # add mysql envriment
      export PATH="{{ software_install_path }}/mysql/bin:${PATH}"
  tags:
    - mysql_make

