# 因为memcached扩展是基于libevent的事件处理的, 首先需要安装libmemcached

# 安装包拷贝
- name: "libmemcached install packge copy"
  copy:
    src: libmemcached-{{ libmemcached_version }}.tar.gz
    dest: "{{ software_save_path }}"
    owner: root
    group: root
  tags:
    - php_memcached_combine

# 判断是否已经安装
- name: "libmemcached already install ?"
  shell: . /etc/profile && . /etc/bashrc && test -d /usr/local/libmemcached/bin ; echo $?
  register: result_install
  changed_when: result_install['stdout']|int != 0
  tags:
    - php_memcached_combine

# 如果没有安装，则：解压、编译、构造、安装
- name: "libmemcached package uncompress, compile, make and make install"
  # 加载环境变量；进入软件包存放路径，删除已解压目录（如果存在的话），解压包；编译；构造；安装
  shell: . /etc/profile && . /etc/bashrc && (cd {{ software_save_path }} && rm -fr libmemcached-{{ libmemcached_version }} && tar xf libmemcached-{{ libmemcached_version }}.tar.gz) && cd {{ software_save_path }}/libmemcached-{{ libmemcached_version }}/ && ./configure --prefix=/usr/local/libmemcached --with-memcached && make && make install
  when: result_install['stdout']|int != 0
  tags:
    - php_memcached_combine

