# 别名设置
- name: "system init alias set"
  blockinfile:
    path: /etc/bashrc
    marker: "### {mark} ANSIBLE MANAGED BLOCK alias_set ###"
    block: |
      # grep color
      alias grep='grep --color=auto'
      alias egrep='grep -E --color=auto'
      alias cp='cp -i'
      alias l.='ls -d .* --color=auto'
      alias ll='ls -l --color=auto'
      alias ls='ls --color=auto'
      alias mv='mv -i'
      alias rm='rm -i'
  tags:
    - base_init
    - alias_set

